feat: Add an option to configure subprocess pool size
getsentry/symbolicator pull request #273
Opened 2020-09-29 13:49 UTC by tonyo

2020-09-29 14:59 UTC, Swatinem approved these changes

2020-09-29 15:10 UTC, jan-auer reviewed
You will also need to update this here, which creates our standard thread pools:

https://github.com/getsentry/symbolicator/blob/2cad3b1924a0b8fcd7a55687ce50a8d104fcf3a9/src/utils/futures.rs#L53

2020-09-29 15:12 UTC, jan-auer requested changes
Sorry, meant to request changes.

2020-09-29 15:24 UTC, tonyo commented
@jan-auer you sure we want to have one setting for everything? Technically, there's also a worker pool in actix HttpServer where we can also adjust worker count
https://github.com/getsentry/symbolicator/blob/master/src/server.rs#L32

2020-09-29 16:17 UTC, jan-auer commented
That's a good question. We may want to split this, indeed. 

Some of these thread pools used to perform CPU-intensive work, but do no longer due to subprocessing. So in that case, we may consider to dial them down independently, so I think your patch is fine.

Should we maybe clarify in docs then that this is the number of sub processes?

2020-09-30 09:57 UTC, flub approved these changes

2020-09-30 14:14 UTC, tonyo commented
@jan-auer updated the docstring, but in the we already have this:

![image](https://user-images.githubusercontent.com/1120468/94697038-014ff000-0338-11eb-91f8-42e27d9809dc.png)

2020-10-01 09:01 UTC, jan-auer approved these changes

2020-10-01 10:53 UTC, merged